/**
 * Talks Hub data for #ntlsn-talkshub (Epic 1.2 PR-B) — the two curated
 * video collections rendered as the "From the Sector" and "International"
 * tabs. Extracted VERBATIM from the production bundle
 * (assets/app.b38bc4ca.js: the sector themes array — 12 themes — and the
 * international themes array — 7 themes). Curated site content by
 * Dr Seb Dianati; every count in the components is derived from here.
 */

export interface TalkVideo {
  title: string;
  org: string;
  url: string;
  note: string;
}

export interface TalkTheme {
  id: string;
  title: string;
  subtitle: string;
  blurb: string;
  icon: string;
  videos: readonly TalkVideo[];
}

/** "From the Sector" — 12 themes, 286 curated talks. */
export const SECTOR_THEMES: readonly TalkTheme[] = [
  {
    id: "genai",
    title: "Generative AI & the Epistemological Disruption",
    subtitle: "From e-cheating panic to distributed cognition",
    blurb: "How GenAI is forcing a fundamental rethink of assessment validity, graduate capabilities, and the nature of human cognition in higher education.",
    icon: "🤖",
    videos: [
      {"title":"Entangled Intelligence? Distributed Cognition, AI Agents & Validity","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=Igmg0FDvW3I","note":"Seminar Series 2026 #4 — the performance paradox of AI-assisted learning"},
      {"title":"Secure Assessment Tasks in a Time of GenAI","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=3mO3Heg_vVU","note":"New Directions in AI #3 — designing AI-resistant assessment"},
      {"title":"Assessment Beyond the Individual Unit/Module","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=KPnSN_23bLg","note":"Seminar Series 2024 #5 — programmatic assessment design"},
      {"title":"ChatGPT Webinar #1 — What Do We Need to Know Now?","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=mCCqf6tHI24","note":"The sector’s first response to ChatGPT"},
      {"title":"ChatGPT Webinar #3 — What Have We Learnt?","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=1V0f3pw2B_0","note":"Consolidating early lessons from the AI disruption"},
      {"title":"ChatGPT Webinar #4 — What Do Researchers Need to Know?","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=Glq-hrmu9HI","note":"Implications for research methodology and ethics"},
      {"title":"Preparing Graduates for an AI-Evolving World (of Work)","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=cI2TYjn56tc","note":"Seminar Series 2026 #2 — the FutureFocus emerging professional self"},
      {"title":"Program-Level Assessment Design and the Two-Lane Approach","org":"ASCILITE","url":"https://www.youtube.com/watch?v=esnEair-RU0","note":"Business Ed SIG — Lane 1 (secure) vs Lane 2 (AI-embracing)"},
      {"title":"Assurance of Learning in the Age of AI","org":"ASCILITE","url":"https://www.youtube.com/watch?v=1m4PpGkEqAA","note":"Satisfying TEQSA while fostering digital literacy"},
      {"title":"AI-Powered Pedagogy: GenAI as Learning Assistant","org":"ASCILITE","url":"https://www.youtube.com/watch?v=Ru6kLQCYk0w","note":"April 2025 webinar on pedagogical AI integration"},
      {"title":"e-Cheating and Assessment Security","org":"ASCILITE / Turnitin","url":"https://www.youtube.com/watch?v=jPohfEAUM1s","note":"ASCILITE Live! — best practices for academic integrity"},
      {"title":"AI in Assessment — 5 Innovative Designs","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=c-wyQFXtFUk","note":"Practical assessment redesigns for the AI era"},
      {"title":"AI Pedagogy Project (AIPP) at UniSQ — Pecha Kucha","org":"CAULLT","url":"https://www.youtube.com/watch?v=fgUeu2vnxIU","note":"Dr Seb Dianati’s institutional AI pedagogy framework"},
      {"title":"Outcome Context Method Venn: Assessment Design in the Age of AI","org":"HERDSA","url":"https://www.youtube.com/watch?v=xve3beUFGs4","note":"Visual method for AI-aware assessment alignment"},
      {"title":"Evaluative Judgement, AI, and Authentic Assessment","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=EunY7Bbgodo","note":"Seminar Series 2024 #4 — AI’s impact on evaluative judgement formation"},
      {"title":"Exploring GenAI’s Scope in Business Education","org":"ASCILITE","url":"https://youtu.be/u-m0-PWYEAE","note":"Business Ed SIG — mapping GenAI applications across business disciplines"},
      {"title":"How Is Business Education Adapting to GenAI?","org":"ASCILITE","url":"https://youtu.be/-Yv5NotFreI","note":"Business Ed SIG — adapting curriculum and assessment for AI-native students"},
      {"title":"What If Your Recent Students Are Already Building the Future of AI?","org":"ASCILITE","url":"https://youtu.be/t7rTLFwLaqA","note":"Business Ed SIG — students as AI co-creators, not just consumers"},
      {"title":"Plugged In, Switched On: AI-Powered Possibilities","org":"HERDSA","url":"https://youtu.be/Pg12N-x2okc","note":"Sector-wide exploration of AI-powered pedagogical innovation"},
      {"title":"TEQSA Request for Information on Gen AI and Assessment","org":"TEQSA","url":"https://www.youtube.com/watch?v=zQhq3-Thljc","note":"Regulator's formal inquiry into GenAI impact on assessment integrity"},
      {"title":"Students Using and Misusing Gen AI for Assessment","org":"TEQSA / Danny Liu","url":"https://www.youtube.com/watch?v=8L_HvZClSnA","note":"Danny Liu — student patterns of AI use and institutional responses"},
      {"title":"Education to Industry: How Gen AI Is Shaping Tomorrow","org":"TEQSA / National AI Centre","url":"https://www.youtube.com/watch?v=cpiCYKRqBLE","note":"Cross-sector panel — GenAI transitions from education to workforce"},
      {"title":"TEQSA Artificial Intelligence Student Advice","org":"TEQSA","url":"https://www.youtube.com/watch?v=8T8oWCgkO-E","note":"Regulatory guidance for students navigating AI in their studies"},
      {"title":"Gen AI in Assessment — Deepfakes and Synthetic Media","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=MlCl_zePwpk","note":"June 2024 — identity verification and deepfake threats to assessment"},
      {"title":"AI in database education (Reihaneh Bidar, UQ)","org":"AI in HE Symposium 2026","url":"","note":"Redesigning database courses around critical reflection of AI-generated SQL."},
      {"title":"Designing for Responsible Collaboration (Armin Alimardani, WSU)","org":"AI in HE Symposium 2026","url":"","note":"Three years of GenAI integration in law assessments."},
      {"title":"Vibe Coding (Reece Sophocleous and James Tsatsaronis, USyd)","org":"AI in HE Symposium 2026","url":"","note":"Low-barrier approach for creating digital teaching resources with GenAI."},
      {"title":"Plugged In, Switched On: AI-Powered Possibilities for Online Engagement","org":"ASCILITE","url":"https://www.youtube.com/watch?v=VPBiQMNnbIQ","note":"June 2025 webinar exploring AI-powered approaches to online student engagement"},
      {"title":"Navigating the Ethical Terrain of AI and Research Integrity","org":"ASCILITE / AARE","url":"https://www.youtube.com/watch?v=mmTx6MzNy04","note":"July 2024 joint webinar on ethics, research integrity, and generative AI"},
      {"title":"Generative AI: Early Sector Responses","org":"ASCILITE","url":"https://www.youtube.com/watch?v=DXB42y-O3Zs","note":"March 2023 webinar capturing the sector’s initial strategic response to GenAI"},
      {"title":"ACODE 90 Workshop: Generative AI and Pedagogies","org":"ACODE","url":"https://www.youtube.com/watch?v=xj-A1h7x6UM","note":"New pedagogies that are music to our ears — GenAI integration workshop"},
      {"title":"TEQSA/CRADLE: Assessment Reform for the Age of AI","org":"TEQSA / CRADLE","url":"https://www.youtube.com/watch?v=8F5jZrFbjJY","note":"Rethinking assessment design to assure learning in a GenAI-ubiquitous world"},
      {"title":"CRADLE (Deakin University) Official Channel","org":"CRADLE (Deakin)","url":"https://www.youtube.com/@cradledeakin9189/videos","note":"Assessment research and digital learning — the sector’s leading assessment research centre"},
      {"title":"Multiple Modalities and Generative AI","org":"Danny Liu","url":"https://www.youtube.com/watch?v=FUpoRTyNvVE","note":"How students use GenAI for multi-modal assessments — practical solutions"},
      {"title":"Professor Phillip Dawson on Assessment Design in a Time of AI","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=_1QKBIP7RnU","note":"Validity in assessment, limits of AI restrictions, programmatic evaluation"},
      {"title":"How Could Generative AI Change Work-Integrated Learning?","org":"CRADLE International Symposium","url":"https://www.youtube.com/watch?v=KhNAz-t06TE","note":"Global panel on intersections of AI, curricula, and workplace learning"},
    ],
  },
  {
    id: "assessment",
    title: "Reimagining Assessment, Feedback & Evaluative Judgement",
    subtitle: "Beyond grades, toward authentic feedback cultures",
    blurb: "The shift from summative grading toward synoptic assessment, psychological authenticity, feedback literacy, and post-critical approaches to evaluation.",
    icon: "📝",
    videos: [
      {"title":"Is It Time to Move Beyond Grades?","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=y6n5vPnnvcc","note":"Seminar Series 2026 #3 — a post-critical approach to grading"},
      {"title":"Reimagining Assessment in Uncertain Times: Part 1 — Synoptic Assessment","org":"HERDSA / ASCILITE","url":"https://www.youtube.com/watch?v=ph4ppV0Nd7I","note":"Cross-institutional dialogues on programmatic redesign"},
      {"title":"Reimagining Assessment in Uncertain Times: Part 2 — The Liminal Zone","org":"HERDSA / ASCILITE","url":"https://www.youtube.com/watch?v=ifUjQfY7l_M","note":"Navigating between dissolved certainties and future designs"},
      {"title":"Why Authenticity Matters in Assessment","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=cOd3X990QA4","note":"Seminar Series 2025 #3 — psychological authenticity via SDT"},
      {"title":"Transforming Feedback Cultures","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=pGDIl-y3ISU","note":"Seminar Series 2025 #5 — sociocultural feedback beyond deficit models"},
      {"title":"What Is the Role of GenAI in Effective Feedback?","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=SC9kJA9Th9o","note":"Seminar Series 2025 #2 — human recognition vs AI efficiency"},
      {"title":"Manifesto for Feedback in the Age of AI","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=GTN6_HqSIfo","note":"Seminar Series 2026 #1 — a values-led compass for institutional policy"},
      {"title":"Mapping Program Learning Outcomes to Assessment Tasks","org":"HERDSA","url":"https://www.youtube.com/watch?v=XqcX8HpsSyo","note":"Making learning visible through outcome alignment"},
      {"title":"Transitions to Authentic Online e-Exams","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=ys9udGhbMHg","note":"e-Exam Symposium — moving beyond proctoring"},
      {"title":"Inclusive Assessment Design: Learning from Adjustments","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=Pb9jr-HFsP4","note":"What disability adjustments teach us about universal design"},
      {"title":"Reimagining Assessment at Scale","org":"ASCILITE / Turnitin","url":"https://www.youtube.com/watch?v=QqD2843o2vk","note":"Joint ASCILITE Live! — large-cohort assessment transformation"},
      {"title":"Assessing Teamwork: Practical Advice","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=UW6VGyyNY8M","note":"Evidence-based approaches to collaborative assessment"},
      {"title":"Assessing Teamwork — Continued","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=pQHEN90x01Q","note":"August 2024 webinar — deeper into team dynamics and peer evaluation"},
      {"title":"Interactive Oral Assessments in First Year","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=_wDfoq8Msbw","note":"Replacing written exams with structured oral interactions"},
      {"title":"Using Peer Assessment to Assess Speaking Skills","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=r3MK72jcxxk","note":"Student-as-assessor models for oral communication"},
      {"title":"Engaging Students Through Agency and Relatedness","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=9fq5NSXtso4","note":"Simon McCallum — SDT-informed assessment for motivation"},
      {"title":"e-Exam System Software and BYOD Exams","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=Uivk7PrQzUc","note":"Secure bring-your-own-device examination infrastructure"},
      {"title":"AI-Assisted Marking Is Here!","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=hD-fY9xXpNw","note":"Automated marking — opportunities, risks, and quality assurance"},
      {"title":"Transforming Assessment for Learning in NZ Schools","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=pxgmGHsxErA","note":"Cross-sector lessons from New Zealand’s school reform"},
      {"title":"How to Stop Student Cheating: A Tier List","org":"HERDSA / P. Dawson","url":"https://www.youtube.com/watch?v=LNcuAmDP2cQ","note":"HERDSA keynote — ranking cheating prevention strategies"},
      {"title":"Transforming Assessment Webinar (June 2014)","org":"Transforming Assessment","url":"http://youtu.be/wsSgFM_GuzQ","note":"Early foundational webinar on assessment transformation"},
      {"title":"Assessment Reform for the Age of Artificial Intelligence","org":"TEQSA / Assoc. Prof. Jason Lodge","url":"https://www.youtube.com/watch?v=GVMHdbbjyoE","note":"Jason Lodge — systemic assessment redesign for the AI era"},
      {"title":"The Academic Misconduct Process Explained (Video 2)","org":"TEQSA","url":"https://www.youtube.com/watch?v=O22TfCa2yuo","note":"TEQSA regulatory guidance on misconduct investigation and process"},
      {"title":"The Shape of Cheating to Come","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=3wSOCmxmbq0","note":"March 2024 — predicting emerging cheating modalities and responses"},
      {"title":"Marking on the Fly: Insights into Interactive Oral Assessments","org":"ASCILITE","url":"https://youtu.be/C96z5Yc5Gdk","note":"Aug 2025 — Alison Casey and colleagues on replacing written exams with structured oral interactions"},
      {"title":"Students as Partners in Assessment","org":"HERDSA","url":"https://adelaide.zoom.us/j/83897140461?pwd=wSKgaFgujU62jUIhnh4gDMEzsmkFGc.1#success","note":"April 2026 webinar on co-designing assessment with students"},
    ],
  },
  {
    id: "indigenous",
    title: "Indigenising the Curriculum & Epistemological Pluralism",
    subtitle: "From performative acknowledgement to ontological transformation",
    blurb: "Moving beyond tokenism to embed Aboriginal and Torres Strait Islander knowledge systems, storying methodologies, and decolonised pedagogy at the core of university teaching.",
    icon: "🌏",
    videos: [
      {"title":"Indigenising the Curriculum: In Practice (Prof. Tracey Bunda)","org":"UQ / AAUT","url":"https://www.youtube.com/watch?v=pq8XQZGBv84","note":"AAUT Career Achievement Award — storying as rigorous methodology"},
      {"title":"For a Legacy of Transformative Leadership in Indigenous Education","org":"UQ / AAUT","url":"https://www.youtube.com/watch?v=HlyuGDZX2LM","note":"Prof. Tracey Bunda — relationality, respect, and reciprocity"},
      {"title":"How to Embed Indigenous Knowledge into Library Collections","org":"ProQuest / UTS","url":"https://www.youtube.com/watch?v=gl78jDHyRBc","note":"Decolonising curatorial practice and cataloguing systems"},
      {"title":"Reflections on Indigenising the Curriculum at ABP","org":"University of Melbourne","url":"https://www.youtube.com/watch?v=KgjehprF8hw","note":"Architecture, Building & Planning faculty case study"},
      {"title":"Developing an Indigenised Curriculum (Microcredential)","org":"UTS Open","url":"https://www.youtube.com/watch?v=RbEjKR1Awzs","note":"Interactive PD for culturally responsive curriculum design"},
      {"title":"Commentary on ‘Indigenising the Curriculum’ and Targeted Hiring","org":"Public Commentary","url":"https://www.youtube.com/watch?v=KVokQl1eyOM","note":"Navigating institutional friction and societal discourse"},
      {"title":"Understanding Country Is Central to Indigenising the Curriculum","org":"HERDSA","url":"https://www.youtube.com/watch?v=TrBd2aThMJE","note":"Place-based pedagogy and Country as teacher — foundational framing"},
      {"title":"Indigenous Knowledges in Action: Transforming Higher Education from the Ground Up","org":"HERDSA","url":"https://www.youtube.com/watch?v=1RGPEVwu2X0","note":"2026 — systemic integration of Indigenous knowledges into university teaching and governance"},
    ],
  },
  {
    id: "sotl-praxis",
    title: "SoTL Praxis & Academic Development",
    subtitle: "From isolated teaching to scholarly, community-driven pedagogy",
    blurb: "Building the infrastructure for scholarly teaching — writing groups, communities of practice, MOOCs, mentoring, and frameworks that connect theory to daily classroom praxis.",
    icon: "🎓",
    videos: [
      {"title":"Contemporary Approaches to University Teaching (CAUT MOOC Welcome)","org":"CAULLT","url":"https://www.youtube.com/watch?v=c7vunFSxg3g","note":"24-module MOOC — 800–1000 enrolments per semester"},
      {"title":"Module 3: Teaching Today’s Diverse Learners","org":"CAULLT","url":"https://www.youtube.com/watch?v=kVRarMpaFjw","note":"CAUT MOOC — engaging non-traditional learners"},
      {"title":"Module 22: Leadership for Learning and Teaching","org":"CAULLT","url":"https://www.youtube.com/watch?v=hOENpSUQAV8","note":"CAUT MOOC — strategic L&T leadership"},
      {"title":"Module 5: Using Technology to Give High Quality Feedback","org":"CAULLT","url":"https://www.youtube.com/watch?v=CUirWuOMU1I","note":"CAUT MOOC — digital feedback strategies"},
      {"title":"Navigating Chaos: The CAULLT Academic Development Awards Day","org":"CAULLT","url":"https://www.youtube.com/watch?v=IVPzd7cXGrU","note":"Celebrating excellence in academic development"},
      {"title":"Designing SoTL Research for Impact","org":"HERDSA","url":"https://www.youtube.com/watch?v=X00KTtfzMmI","note":"Dr Jo-Anne Kelder — measuring pedagogical intervention impact"},
      {"title":"Impact of Writing Groups on Academic Publishing Success","org":"HERDSA","url":"https://www.youtube.com/watch?v=KH51qMSHDRs","note":"HERDSA 2026 poster — identity formation through scholarly writing"},
      {"title":"Writing a Great ASCILITE Paper","org":"ASCILITE","url":"https://www.youtube.com/user/ascilite/videos","note":"ASCILITE Live! — demystifying the publication process"},
      {"title":"LD SIG Research Mentoring Webinar","org":"ASCILITE","url":"https://www.youtube.com/watch?v=pCoqLl9LJVg","note":"Learning Design SIG — structured mentoring pathways"},
      {"title":"TATAL Communities of Practice Webinar","org":"HERDSA","url":"https://herdsa.org.au/news/welcome-tatal-webinar-2025","note":"Talking About Teaching and Learning — collegial reflection"},
      {"title":"Inside IJAD: What We Learned from Four Journal Editors","org":"HERDSA","url":"https://herdsa.org.au/news/inside-ijad-what-we-learned-four-journal-editors-about-getting-published","note":"Getting published in International Journal for Academic Development"},
      {"title":"Courageous Thinkers Graduate Attribute Integration","org":"UQ ITaLI","url":"https://itali.uq.edu.au/teaching-guidance/curriculum-design-and-review/graduate-attributes/videos-on-graduate-attributes","note":"Embedding graduate attributes across programs"},
      {"title":"CRADLE 10th Anniversary Celebration","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=syz6cwTGkSU","note":"A decade of assessment and digital learning research leadership"},
      {"title":"ASCILITE 2018 Conference Day 2 Report","org":"ASCILITE","url":"https://www.youtube.com/watch?v=XLNEapcDlVg","note":"Conference highlights — technology-enhanced learning trends"},
      {"title":"ASCILITE 2019 Keynote Preview (Prof. Koh)","org":"ASCILITE","url":"https://www.youtube.com/watch?v=9158Rbp-PTM","note":"Previewing keynote themes in digital education"},
      {"title":"ASCILITE 2013: Designer, Writer, Scholar","org":"ASCILITE","url":"https://www.youtube.com/watch?v=cU6Gk0bRoyQ","note":"Early framing of learning design as scholarly practice"},
      {"title":"Sharing Responsibility with Suppliers (Business Ed SIG)","org":"ASCILITE","url":"https://www.youtube.com/watch?v=oXhby9qz0uU","note":"Industry partnership models in business education pedagogy"},
      {"title":"Responsible Business Education for All","org":"ASCILITE","url":"https://youtu.be/9ssLNKkXcWY","note":"Business Ed SIG — ethics, sustainability, and inclusive curriculum"},
      {"title":"To Use Live Clients or Not to Use Live Clients?","org":"ASCILITE","url":"https://www.youtube.com/watch?v=CELq0a8Qke4","note":"Business Ed SIG — authentic assessment with real stakeholders"},
      {"title":"Academic Development SIG","org":"HERDSA","url":"https://www.youtube.com/watch?v=zl77t7sLkcA","note":"SIG overview — professional identity and academic developer roles"},
      {"title":"HERDSA 2025 Virtual Presentation (Claudia Gottwald)","org":"HERDSA","url":"https://www.youtube.com/watch?v=cnHY4zqdeP8","note":"International perspective on academic development practice"},
      {"title":"Sustainability in Learning and Teaching: Making It Happen","org":"HERDSA","url":"https://www.youtube.com/watch?v=VTnTC-D8udM","note":"Embedding sustainability across curriculum and pedagogy"},
      {"title":"Helen Sword on Academic Writing","org":"HERDSA","url":"https://www.youtube.com/watch?v=V9Mw2NPWUXE","note":"Writing-related resources — stylish academic writing in practice"},
      {"title":"Jennifer Stokes on Course Design and Contemporary Students","org":"HERDSA","url":"https://www.youtube.com/watch?v=r3BqI2l1Xpk","note":"Designing for today’s learner demographics and expectations"},
      {"title":"Pedagogy of Belonging & Wellbeing SIG Insights","org":"HERDSA","url":"https://www.youtube.com/watch?v=68ZzPkZvLzs","note":"Student belonging, mental health, and relational pedagogy"},
      {"title":"Module 22: Quality Assurance Welcome","org":"CAULLT","url":"https://www.youtube.com/watch?v=KmLxbvJmYYI","note":"CAUT MOOC — quality assurance frameworks in L&T"},
      {"title":"Celebrating 10 Years of ITaLI","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=0IgEQ4xhgRs","note":"A decade of teaching and learning innovation at UQ"},
      {"title":"Connected Citizens and Respectful Leaders","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=4U46FS_M1Pc","note":"Graduate attribute integration — civic engagement and leadership"},
      {"title":"Courageous Thinkers Graduate Attribute","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=1QYop7OVrMs","note":"Embedding critical thinking as a program-level outcome"},
      {"title":"What’s Working — The Student Edition","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=G1r-OMB8hXY","note":"Students share what teaching practices work best"},
      {"title":"National Tertiary Teaching Excellence Award Winners","org":"NTLSN / Univ. of Auckland","url":"https://www.youtube.com/watch?v=R8G704g16wY","note":"Celebrating cross-Tasman teaching excellence"},
      {"title":"Bachelor of Culinary Arts (BCA) Team Showcase","org":"NTLSN / NTO","url":"https://www.youtube.com/watch?v=2udLMsI6icU","note":"Vocational excellence — team-based teaching innovation"},
      {"title":"The Australian Universities Accord: Transforming Big Ideas into Real-World Reform","org":"TEQSA (#TEQSA24)","url":"https://www.youtube.com/watch?v=pSYr04ZoQ7I","note":"#TEQSA24 — turning Accord recommendations into sector action"},
      {"title":"Current Issues for Regulation in the Higher Education Sector","org":"TEQSA (#TEQSA23)","url":"https://www.youtube.com/watch?v=wWky0fFvg5w","note":"#TEQSA23 — regulatory priorities including AI, quality, and equity"},
      {"title":"TEQSA Talks #2, 2025","org":"TEQSA","url":"https://www.youtube.com/watch?v=fpR4Qaetdug","note":"TEQSA Talks series — contemporary regulatory discussions"},
      {"title":"TEQSA Talks #3, 2025","org":"TEQSA","url":"https://www.youtube.com/watch?v=pA7CWwEd2bQ","note":"TEQSA Talks series — continued sector regulation dialogues"},
      {"title":"Making Work Integrated Learning Work: For Us, for Students, and for the Curriculum","org":"WIL Australia / UniMelb / ECU / La Trobe","url":"https://www.youtube.com/watch?v=BCjVPBvbuCs","note":"Multi-institutional perspectives on embedding WIL at scale"},
      {"title":"WIL Communities of Practice: Research into Institutional Practices","org":"WIL Australia","url":"https://www.youtube.com/watch?v=TfsuvGm5V9o","note":"Sector-wide WIL research and institutional practice sharing"},
      {"title":"Work Integrated Learning — Building Sustainable Collaborative Partnerships","org":"HERDSA","url":"https://www.youtube.com/watch?v=UWlcy3lvBtw","note":"HERDSA — sustainable industry-university WIL partnerships"},
      {"title":"What’s It Like to Be on the ASCILITE Executive Board?","org":"ASCILITE","url":"https://www.youtube.com/watch?v=ovoAstzrOhU","note":"Sept 2025 — demystifying sector leadership and governance roles"},
      {"title":"ASCILITE 2023 Innovation Award: myBCom","org":"ASCILITE","url":"https://www.youtube.com/watch?v=R4k0FOHz2qc","note":"Award-winning innovation in business education curriculum design"},
      {"title":"Paulo Freire’s Pedagogy of the Oppressed (Summary)","org":"Various","url":"https://www.youtube.com/watch?v=vazSwO1MoZ0","note":"Banking model vs problem-posing education — essential for critical teaching philosophies"},
      {"title":"Constructivism in Education","org":"Various","url":"https://www.youtube.com/watch?v=am-bJARXqN0","note":"Cognitive constructivism (Piaget) vs social constructivism (Vygotsky) in instructional design"},
      {"title":"Introduction to SoTL Methodologies","org":"Various","url":"https://www.youtube.com/watch?v=R90v2uF4pBE","note":"Formulating SoTL research questions and aligning to appropriate paradigms"},
      {"title":"Action Research in the Classroom","org":"Various","url":"https://www.youtube.com/watch?v=r0XJ6K8yIcw","note":"Iterative Action Research cycle: Plan, Act, Observe, Reflect"},
      {"title":"Publishing Your SoTL Research","org":"Journal Editors Panel","url":"https://www.youtube.com/watch?v=F_3v0b9E9e4","note":"What makes a SoTL manuscript competitive — theory, methodology, data analysis"},
      {"title":"CRADLE Seminar: Developing Feedback Literacy","org":"CRADLE (Deakin)","url":"https://www.youtube.com/watch?v=wYJB3IXtuIA","note":"Case studies from multiple disciplines on building student feedback literacy"},
    ],
  },
  {
    id: "tel",
    title: "Technology-Enhanced Learning, Analytics & Hybrid Spaces",
    subtitle: "From ad-hoc edtech to governed digital ecosystems",
    blurb: "Strategic benchmarking, learning analytics, inclusive digital design, and the intentional blending of physical and digital spaces for active collaborative learning.",
    icon: "💻",
    videos: [
      {"title":"ACODE Benchmarking 2026 Introduction","org":"ACODE","url":"https://www.youtube.com/watch?v=9O-vHYhr6QY","note":"8-dimension self-evaluation for institutional digital capacity"},
      {"title":"DIGI-HE: A Strategic Reflection on Digitalisation in Higher Education","org":"ACODE / EUA","url":"https://www.youtube.com/watch?v=AjvQZDDfdhY","note":"European University Association framework for digital maturity"},
      {"title":"Access Granted: Pioneering Inclusive Education","org":"ACODE / ICDE","url":"https://acode.edu.au/newsletter/2025/access-granted-webinar/","note":"Digital accessibility and Benchmark 10"},
      {"title":"What Motivates Students to Learn? (Learning Analytics SIG)","org":"ASCILITE","url":"https://www.youtube.com/watch?v=fL4PcVK6ltg","note":"Dr Paula de Barba — SDT meets data science"},
      {"title":"Designing Spaces for Connection: Evolving Insights from CONNECTspace","org":"ASCILITE","url":"https://www.youtube.com/watch?v=G9yFPxD89jo","note":"USyd Business School — physical-digital hybrid architecture"},
      {"title":"RiPPLE: A Study and Active Learning Tool","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=fyrE5TOqMGk","note":"Crowdsourced adaptive learning at scale"},
      {"title":"Online Engagement in HE SIG Event","org":"HERDSA","url":"https://www.youtube.com/watch?v=_cj4z3pwYqw","note":"Fostering connection and mitigating isolation online"},
      {"title":"Online Engagement SIG Lightning Talks — Key Takeaways","org":"HERDSA","url":"https://herdsa.org.au/news/herdsa-online-engagement-he-sig-lightning-talks-key-takeaways","note":"Rapid-fire innovations in online teaching"},
      {"title":"Design Principles for Human-Centred Learning Analytics","org":"ASCILITE","url":"https://www.youtube.com/watch?v=HbOtLdgetT0","note":"LA SIG — putting students at the centre of analytics design"},
      {"title":"Digging Deeper into the Ethical Use of Learning Analytics","org":"ASCILITE","url":"https://www.youtube.com/watch?v=p1TWpp6NwwA","note":"LA SIG — privacy, consent, and responsible data use"},
      {"title":"Introducing the Learning Design SIG","org":"ASCILITE","url":"https://www.youtube.com/watch?v=lLDrVtbpwBQ","note":"Learning design as a discipline — SIG overview and goals"},
      {"title":"Introducing the Learning Design SIG (Alternate Overview)","org":"ASCILITE","url":"https://www.youtube.com/watch?v=LJguNoKpXwU","note":"Extended introduction to LD SIG activities and membership"},
      {"title":"TELedvisors SIG: Listen to Your Edvisors","org":"ASCILITE","url":"https://www.youtube.com/watch?v=jE9gQ0PbbTk","note":"The role of educational technology advisors in institutions"},
      {"title":"TELedvisors SIG: Preparing for ASCILITE 2022","org":"ASCILITE","url":"https://www.youtube.com/watch?v=GYzKQ7_XLE4","note":"Pre-conference SIG preparation and community building"},
      {"title":"Mobile and Social Media Technologies in Education","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=z2j6FhW1QFI","note":"Early sector exploration of mobile-first learning design"},
      {"title":"Online Engagement SIG Lightning Talks (Extended)","org":"HERDSA","url":"https://youtu.be/msMGMs60VYg","note":"Additional lightning talks on fostering online community"},
      {"title":"Learn UQ Basics — Ready to Teach Week S2","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=f-6JfJsjtgQ","note":"LMS foundations — getting started with institutional TEL"},
      {"title":"Supporting Technology-Enhanced Learning","org":"UQ ITaLI","url":"https://www.youtube.com/watch?v=EGwls3woibc","note":"Institutional TEL support models and staff enablement"},
      {"title":"EPortfolio Stories from Down Under: Historical Reflections on Pedagogy and Practice","org":"ePortfolios Australia","url":"https://www.youtube.com/watch?v=SdQrZG25pI8","note":"2024 — tracing Australasian ePortfolio practice and its evolution"},
      {"title":"Building Digital Resilience Through ePortfolios","org":"AAEEBL / FLANZ / ePortfolios Australia","url":"https://www.youtube.com/watch?v=uAJ5cGXBTeg","note":"2026 — ePortfolios as infrastructure for lifelong digital resilience"},
      {"title":"Workshop: How to Get Started with AI Tools in Portfolios","org":"ePortfolios Australia","url":"https://www.youtube.com/watch?v=mLZEWupiFYM","note":"2023 workshop — integrating generative AI into ePortfolio practice"},
      {"title":"OA Week 2024: Open and Accessible — When Open Isn't Enough","org":"CAUL","url":"https://www.youtube.com/watch?v=PugMfqJ3HxY","note":"CAUL panel — accessibility, equity, and the limits of open access"},
      {"title":"Sylla Discover Platform: Adopting OA/OER","org":"CAUL / Deakin","url":"https://www.youtube.com/watch?v=_WPA6nRhn1s","note":"Discovery platform for open access and open educational resources"},
      {"title":"2022 ASCILITE Student Bursary: Benefits and Considerations of Digital Badges","org":"ASCILITE","url":"https://www.youtube.com/watch?v=rz_23kXjfoU","note":"Student research on microcredentialing and digital badge ecosystems"},
      {"title":"Strategies for Developing Rapport Between Educators and Students in FTF and Online","org":"ASCILITE","url":"https://www.youtube.com/watch?v=l-y4_1U2XuQ","note":"June 2023 — building connection across modalities"},
      {"title":"Batman: The Online Clinical Classroom","org":"ASCILITE","url":"https://www.youtube.com/watch?v=_MgCfmPyeRs","note":"July 2021 — innovative clinical simulation in online learning"},
      {"title":"ACODE Virtual Workshop July 2019","org":"ACODE","url":"https://www.youtube.com/watch?v=EcG7k4BWyUo","note":"Benchmarking and digital learning strategy workshop"},
      {"title":"Assurance of Learning Channel","org":"AoL Hub","url":"https://www.youtube.com/channel/UCAkJE1mqSPgKHwCY8AH-prA/videos","note":"Conceptual videos on program mapping, institutional motivation, and AoL principles"},
      {"title":"CAST (Creators of the UDL Framework)","org":"CAST","url":"https://www.cast.org/","note":"Official UDL webinars, masterclasses, and UDL 3.0 rollout updates"},
      {"title":"ASCILITE Official Channel","org":"ASCILITE","url":"https://www.youtube.com/@ascilite","note":"Technology-enhanced learning, AI integrations, learning analytics across Australasia"},
      {"title":"Advance HE Channel","org":"Advance HE","url":"https://www.youtube.com/@AdvanceHE","note":"HE governance, partnership frameworks, critical pedagogy, inclusive curriculum design"},
      {"title":"Active Learning in Higher Education","org":"Various","url":"https://www.youtube.com/watch?v=-0RJCKPcWLo","note":"Collaborative learning principles and strategies to shift away from passive lectures"},
      {"title":"Active Learning: Higher Ed Teaching & Learning","org":"UBC / Various","url":"https://www.youtube.com/watch?v=LhlkZuC8Kzc","note":"Evidence-based active learning approaches and learning space designs"},
      {"title":"Next-Level Active Learning in Higher Education","org":"Various","url":"https://www.youtube.com/watch?v=gEoeNY7DMPs","note":"Evidence-based active learning strategies and overcoming faculty hesitation"},
      {"title":"Leading the Way: Curriculum Design for Learning","org":"Various","url":"https://www.youtube.com/watch?v=hEycgEbE0PY","note":"How curriculum development programs structure evidence for HEA Fellowship"},
      {"title":"Linking Learning Outcomes Through Curriculum Mapping","org":"Harvard HILT","url":"https://www.youtube.com/watch?v=oOEsvwxlpVs","note":"Creating curriculum mapping tools to identify knowledge gaps across programs"},
      {"title":"Curriculum Mapping Fundamentals","org":"Various","url":"https://www.youtube.com/watch?v=hKWvad_8dGg","note":"Mapping HE curriculum to program-level Student Learning Outcomes"},
      {"title":"Best Practices in Curriculum Design and Planning","org":"Various","url":"https://www.youtube.com/watch?v=lo3wKdF8Meo","note":"Design thinking for student-centred learning experiences in tertiary settings"},
      {"title":"ABC Learning Design Method Supports Innovation","org":"UCL","url":"https://www.youtube.com/watch?v=vh0C3K4oRYY","note":"UCL co-creators on rapid collaborative curriculum storyboarding"},
      {"title":"Aligning ABC Learning Design with Moodle & Canvas","org":"UCL","url":"https://www.youtube.com/watch?v=3C1gTHApg8A","note":"APT methodology — translating storyboards into live LMS environments"},
      {"title":"The 5-Stage Model of E-learning (Gilly Salmon)","org":"Gilly Salmon","url":"https://www.youtube.com/watch?v=EaB385Yn9o8","note":"Scaffolding online engagement from access and motivation to knowledge construction"},
      {"title":"ASCILITE LD SIG: Learning Design Research — Continuing the Discourse","org":"ASCILITE","url":"https://www.youtube.com/watch?v=Y5sRuy-vfVQ","note":"Learning Design SIG research seminar on advancing the discourse"},
    ],
  },
  {
    id: "symposia",
    title: "Symposia, Conferences & Sector Events",
    subtitle: "Live and archived events shaping the national conversation",
    blurb: "Key conferences, symposia, and professional events from ATN, ASCILITE, WIL Australia, CAUL, THE, and other sector bodies driving dialogue on teaching, learning, and university futures.",
    icon: "🎤",
    videos: [
      {"title":"ATN National Symposium on GenAI and Graduate Employability","org":"ATN","url":"https://www.youtube.com/watch?v=Z-HgG0pf-W4","note":"A comprehensive 3-hour recording focusing on how Generative AI intersects with graduate outcomes and employability sk..."},
      {"title":"ATN National Symposium: GenAI and Graduate Employability Showcase Video","org":"ATN","url":"https://www.youtube.com/watch?v=IdxI3OEEM-c","note":"A condensed 30-minute showcase highlighting key takeaways and presentations from the GenAI symposium."},
      {"title":"ATN International Education Summit - Day One","org":"ATN","url":"https://www.youtube.com/watch?v=p4OIf7l-Y5U","note":"A full 2-hour summit session discussing international education strategies, partnerships, and challenges."},
      {"title":"ASCILITE Live! Webinar - Making your conference presentations more accessible","org":"ASCILITE","url":"https://www.youtube.com/watch?v=2p7dPtsNOOw","note":"A practical 46-minute professional development workshop on creating inclusive academic materials."},
      {"title":"BE-SIG May 2026 webinar: Discussing the Castlereagh Statement","org":"ASCILITE","url":"https://www.youtube.com/watch?v=VOJ0Ezy_Irc","note":"Session from ASCILITE’s Business Education Special Interest Group (BE-SIG)."},
      {"title":"#Ascilite Symposium","org":"ASCILITE","url":"https://www.youtube.com/watch?v=JDGrV4IHzC8","note":"An archived 46-minute presentation session from a previous ASCILITE symposium."},
      {"title":"ACEN 2024 Conference - Keynote","org":"WIL Australia","url":"https://www.youtube.com/watch?v=CoqdIhbgTFM","note":"A keynote segment from the Australian Collaborative Education Network's 2024 annual conference."},
      {"title":"Learning Through Design Conference (25–27 August 2026)","org":"CQUni","url":"https://lts.cqu.edu.au/conf/","note":"Focus on Collaboration, Inclusion, AI, Assessment, and Students as Partners."},
      {"title":"UNE L&T Symposium: Student Voice and Engagement (July 21, 2026)","org":"UNE","url":"https://symposium.une.edu.au/symposium-2026/student-voice-student-engagement/","note":"Keynote by Prof Jason M. Lodge on AI and digital tech learning mechanisms. Hybrid format."},
      {"title":"2026 QILT Symposium (May 19, 2026)","org":"QILT / UNSW","url":"https://www.youtube.com/watch?v=bXF3rcB2xiQ","note":"QILT data drivers of teaching quality and student retention. Includes USYD and UNSW presentations."},
      {"title":"Election Watch: Geopolitics with Phil Honeywood","org":"ATN Podcast","url":"https://www.atn.edu.au/","note":"ATN podcast series discussing geopolitics and the federal election."},
      {"title":"What is the future for higher education?","org":"ATN Podcast","url":"https://www.atn.edu.au/","note":"UTS Panel Discussion on the future of HE."},
      {"title":"Building research culture and reputation through scalable systems (4 June 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Addressing systems for collaboration and standardization in research."},
      {"title":"Empowering the modern learner: Redesigning student support (21 April 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Best practices on providing proactive, prevention-first student support."},
      {"title":"Academic integrity under fire: Fortifying assessment in an AI-mediated world (13 May 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Addressing how institutions are rethinking assessment."},
      {"title":"IHE US AI Summit 2026 (3-4 June 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Shaping the future of AI in the service of society. Buffalo, NY."},
      {"title":"Global Sustainable Development Congress 2026 (22-25 June 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Driving alliances for a more sustainable future. Jakarta, Indonesia."},
      {"title":"Digital Universities Asia 2026 (24-25 September 2026)","org":"Times Higher Education","url":"https://www.timeshighereducation.com/","note":"Elevating university excellence to power Asia’s digital future. Chengdu, China."},
      {"title":"Collections Analysis CoP 2026 (June 3, Aug 5)","org":"CAUL","url":"https://www.caul.edu.au/","note":"Council of Australasian University Librarians Community of Practice."},
      {"title":"Learning and Teaching Leaders CoP 2026 (June 11, July 9, Aug 13, Sept 10)","org":"CAUL","url":"https://www.caul.edu.au/","note":"CAUL Learning and Teaching Leaders Community of Practice."},
      {"title":"Australian Scholarly Comms Community of Practice 2026 (June 16, July 21, Aug 18, Sept 15)","org":"CAUL","url":"https://www.caul.edu.au/","note":"CAUL Scholarly Communications meetings."},
      {"title":"CAUL Exhibition Event 2026","org":"CAUL","url":"https://www.caul.edu.au/","note":"Exhibitions in Wellington (June 16), Melbourne (June 18), Sydney (June 19)."},
    ],
  },
  {
    id: "sankey-digital",
    title: "Digital Learning Leadership & Strategy",
    subtitle: "Sector architects on benchmarking, platforms, and transformation",
    blurb: "Strategic perspectives on digital learning infrastructure, ACODE benchmarking, and institutional transformation from leaders including Professor Michael Sankey.",
    icon: "📡",
    videos: [
      {"title":"Quality Assurance of Online Learning: Michael Sankey, ACODE’s Work on Benchmarking","org":"ACODE / TEQSA","url":"https://www.youtube.com/watch?v=_o4DH6Yw0hs","note":"Presented at TEQSA; covers developing benchmarks for technology-enhanced learning."},
      {"title":"Higher Education Remote Learning Series: Professor Michael Sankey","org":"Microsoft ANZ","url":"https://www.youtube.com/watch?v=tdmFDfkvudg","note":"Hosted by Microsoft ANZ; explores digital strategy, academic development, and learning platforms."},
      {"title":"A Conversation about Learning Transformation for Rural Universities","org":"Microsoft ANZ","url":"https://www.youtube.com/watch?v=lmuVqfdl4mg","note":"Discussion focusing on how regional and rural institutions manage educational technology."},
      {"title":"TELedvisors Webinar: Michael Sankey","org":"ASCILITE","url":"https://www.youtube.com/watch?v=WiNVTAeheH0","note":"Webinar discussing the evolving roles of educational technologists and learning designers."},
      {"title":"The Student Learning Journey - TIU Breakfast Session","org":"ASCILITE","url":"https://www.youtube.com/watch?v=SFf_7TeN2IY","note":"Presentation at UniSA on mapping and supporting the digital student experience."},
      {"title":"Some Trends for Australian HE and VET: Learning to Be Agile for 2023","org":"Prof. Michael Sankey","url":"https://www.youtube.com/watch?v=I1FrDz9MCuQ","note":"Emerging trends influencing HE and VET sectors — institutional agility and digital strategy"},
      {"title":"An Introduction to the Scholarship of Teaching and Learning (SoTL)","org":"SoTL Workshop","url":"https://www.youtube.com/watch?v=eV0_wCOFRXk","note":"Practical workshop on classroom-based research and disseminating findings publicly"},
      {"title":"History of the Scholarship of Teaching and Learning","org":"Center for Engaged Learning","url":"https://www.youtube.com/watch?v=gYiyxQGa480","note":"Panel of leading academics on the foundational history and evolution of SoTL"},
      {"title":"Examples of SoTL Projects","org":"Various Universities","url":"https://www.youtube.com/watch?v=LogmkiN6utk","note":"Scholars share concrete examples of SoTL projects and practical methodologies"},
      {"title":"Why Integrate Student Voices in SoTL?","org":"SoTL Panel","url":"https://www.youtube.com/watch?v=4LbKSkqr06Y","note":"Panel on the pedagogical necessity of integrating student perspectives into SoTL"},
      {"title":"Professor Michael Sankey (Personal Channel)","org":"Prof. Michael Sankey","url":"https://www.youtube.com/c/MichaelSankey","note":"Multimodal design, digital literacies, and emerging technologies in higher education"},
      {"title":"The ACODE Learning Leaders Vodcast Series","org":"ACODE / Michael Sankey","url":"https://www.youtube.com/channel/UCQHtUlUwqNy5Txa4thrlmlw/","note":"Video interviews with key leaders in technology-enhanced learning across Australasia"},
    ],
  },
  {
    id: "udl",
    title: "Universal Design for Learning & Inclusive Education",
    subtitle: "From compliance to genuine belonging",
    blurb: "Implementing UDL at scale, digital accessibility, AI for inclusion, and designing learning environments where every student can thrive.",
    icon: "♿",
    videos: [
      {"title":"What is UDL? Professor Terry Cumming (UNSW)","org":"UNSW","url":"https://www.youtube.com/watch?v=6O5A9p_d8bU","note":"Breakdown of UDL from the University of New South Wales perspective."},
      {"title":"Universal Design for Learning (Teaching to diversity)","org":"Teaching to diversity","url":"https://www.youtube.com/watch?v=qxrA0VVNQ44","note":"Charles Sturt University overview of using UDL principles for diverse cohorts."},
      {"title":"Introduction of Universal Design for Learning","org":"Various","url":"https://www.youtube.com/watch?v=SEe_9brf95Q","note":"Explainer from RMIT’s Learning and Teaching unit on the basics of UDL."},
      {"title":"Applying UDL within an Academic Library","org":"Various","url":"https://www.youtube.com/watch?v=FQ0CQHjTh_E","note":"Explores how academic libraries can apply UDL for accessible resources (Griffith College)."},
      {"title":"ADCET Webinar: Implementing Universal Design for Learning (UDL) at the University of Sydney","org":"ADCET","url":"https://www.youtube.com/watch?v=kjpqakhht4o","note":"Details how the University of Sydney rolled out UDL principles across their tertiary curriculum."},
      {"title":"Institution-wide Embrace of Universal Design for Learning","org":"ADCET","url":"https://www.youtube.com/watch?v=yBwlVwiI328","note":"Presentation focusing on the strategic, top-down implementation of UDL across an entire institution."},
      {"title":"Toward an Institutional Wide Approach for Embedding UDL","org":"ADCET","url":"https://www.youtube.com/watch?v=Uupz4ZmlAoU","note":"Insights into the administrative and academic strategies required to make UDL the default standard."},
      {"title":"The UDL Quandary of Organisational Implementation","org":"ADCET","url":"https://www.youtube.com/watch?v=u2CaW30WS4Q","note":"Deep dive into the bureaucratic and logistical challenges of implementing UDL in higher education."},
      {"title":"Developing an inclusive curriculum and teaching team culture using UDL","org":"ADCET","url":"https://www.youtube.com/watch?v=6vqi9Wj2qro","note":"Focuses on training teaching teams and redesigning curricula to natively support inclusivity."},
      {"title":"Teaching at Torrens - Using UDL for accessible education","org":"ADCET","url":"https://www.youtube.com/watch?v=USpUjctAInU","note":"A poster presentation from Torrens University exploring their approach to UDL."},
      {"title":"Levelling Up Your Online Teaching with Universal Design for Learning","org":"ADCET","url":"https://www.youtube.com/watch?v=pYgeuN54tkw","note":"Workshop on translating UDL principles specifically into online learning environments."},
      {"title":"Implementing innovative and effective UDL 3.0 in your classroom","org":"ADCET","url":"https://www.youtube.com/watch?v=w3DRhT-vcEE","note":"A look at the latest iteration of the UDL framework (3.0) and classroom application."},
      {"title":"ADCET UDL Symposium 2025: Rethinking Examinations in the Age of AI","org":"ADCET","url":"https://www.youtube.com/watch?v=ny9SCX2pzzY","note":"Explores how AI is forcing a redesign of assessments and how UDL ensures inclusivity."},
      {"title":"Harnessing Generative AI to Empower Inclusive Education","org":"ADCET","url":"https://www.youtube.com/watch?v=1wSWSSu4itM","note":"Detailed look at how GenAI can act as an assistive technology and support inclusive teaching."},
      {"title":"Bicycle for the mind: AI for Accessibility","org":"ADCET","url":"https://www.youtube.com/watch?v=77ZftVEBhMk","note":"Explores AI tools as a means for greater digital and cognitive accessibility (AI in Higher Ed Symposium)."},
      {"title":"ADCET webinar: The Inclusive Classroom","org":"Various","url":"https://www.youtube.com/watch?v=CAKEdfPmZXc","note":"Focusing on the day-to-day practices that foster an inclusive environment for students with disabilities."},
      {"title":"Inclusive Education: Tertiary Education for People with Intellectual Disability","org":"Various","url":"https://www.youtube.com/watch?v=UkHNazl-UgU","note":"Critical discussion on support structures for neurodiverse and intellectually disabled students."},
      {"title":"Vision Australia Digital Access webinar: Designing for Everyone","org":"Vision Australia","url":"https://www.youtube.com/watch?v=d-EluYU6qIA","note":"Introduction to digital accessibility and inclusive design principles."},
      {"title":"Why Digital Accessibility & Inclusive Design Matters","org":"UX Australia","url":"https://www.youtube.com/watch?v=YGdXravvI9E","note":"UX Australia presentation on the user experience side of digital accessibility."},
      {"title":"NUspace Behind The Design Series - Accessibility","org":"University of Newcastle","url":"https://www.youtube.com/watch?v=nKUcjmPbh68","note":"University of Newcastle's look at the physical accessibility of the NUspace campus."},
      {"title":"2026 AI in Higher Education ANZ Symposium (February 3, 2026)","org":"AI in HE Symposium 2026","url":"","note":"Multiple streams including redesigning assessments, AI agents, student critique, and ethical agency."},
      {"title":"Getting to Know the New UDL 3.0 Guidelines","org":"Temple University","url":"https://www.youtube.com/watch?v=KTu5VMUIiaE","note":"Walkthrough of the 2024 UDL Guidelines 3.0 update — new structure, language, and systemic focus"},
      {"title":"UDL 3.0: Changes to Action and Expression","org":"CAST","url":"https://www.youtube.com/watch?v=3gvlFPvMpUc","note":"CAST deep-dive into how Action & Expression evolved in the 3.0 framework"},
      {"title":"UDL 3.0: Changes to Representation","org":"CAST","url":"https://www.youtube.com/watch?v=Pvph1RN2szA","note":"CAST deep-dive into the Representation principle updates in UDL 3.0"},
      {"title":"An Introduction to Universal Design for Learning","org":"Humber College","url":"https://www.youtube.com/watch?v=ONPINQR_Wes","note":"Accessible primer on core UDL principles for higher education practitioners"},
      {"title":"A Crash Course in UDL (Inclusive Learning)","org":"Katie Novak / Toddle","url":"https://www.youtube.com/watch?v=T-4--_rjvII","note":"Katie Novak's concise overview of UDL implementation for time-poor educators"},
      {"title":"UDL On Campus: Assessment in Higher Education","org":"CAST / UDL On Campus","url":"https://www.youtube.com/channel/UCJxjhBZnKoSuTHn7wGowezQ","note":"CAST channel — curated collection on UDL-aligned assessment design in tertiary contexts"},
      {"title":"UDL On Campus: Improving Institutional Policies","org":"CAST / UDL On Campus","url":"https://www.youtube.com/channel/UCJxjhBZnKoSuTHn7wGowezQ","note":"CAST channel — policy-level resources for embedding UDL across institutions"},
      {"title":"UDL On Campus: Planning Your Course","org":"CAST / UDL On Campus","url":"https://www.youtube.com/channel/UCJxjhBZnKoSuTHn7wGowezQ","note":"CAST channel — practical course planning resources using UDL principles"},
      {"title":"Universal Design for Learning for College Students","org":"Arendale UDL Channel","url":"https://www.youtube.com/@universaldesignforlearning","note":"Comprehensive YouTube channel dedicated to UDL resources for tertiary learners"},
      {"title":"Universal Design for Learning in Higher Education","org":"Humber College","url":"https://www.youtube.com/watch?v=VwA8cQ2xA9o","note":"Three core UDL principles with direct applications for inclusive university learning"},
      {"title":"Empowering Students as Partners for Sustainability","org":"Global Workshop","url":"https://www.youtube.com/watch?v=eoRLo6qV5vM","note":"Engaging students as genuine partners in transforming curricula and learning environments"},
      {"title":"How to Conduct Assurance of Learning for CQI","org":"Academic Quality","url":"https://www.youtube.com/watch?v=FKYTN3xMTUU","note":"Evaluation cycle — applying assessment results to drive continuous quality improvement"},
      {"title":"Universal Design for Learning in Higher Education (CAST)","org":"CAST","url":"https://www.youtube.com/watch?v=jTEIGX_MaAA","note":"Building multiple means of representation, action, and expression into assessments"},
    ],
  },
  {
    id: "sap",
    title: "Students as Partners & Co-Creation",
    subtitle: "From consultation to genuine power-sharing",
    blurb: "Student voice, co-creation, power dynamics, and institutional transformation through genuine student-staff partnership across Australasian universities.",
    icon: "🤝",
    videos: [
      {"title":"Students as Partners at Victoria University","org":"Student Voice Australasia","url":"https://www.youtube.com/watch?v=vD_8xgcifWc","note":"Details how Victoria University integrated the SaP framework into their block-model curriculum."},
      {"title":"Student Leadership Plan: Students as Partners","org":"Student Voice Australasia","url":"https://www.youtube.com/watch?v=Pz8pohQfhB0","note":"Focuses on redesigning student leadership initiatives as genuine partnerships."},
      {"title":"2019 National Students as Partners Vox Pops","org":"Student Voice Australasia","url":"https://www.youtube.com/watch?v=PA_to-LVxqE","note":"UNSW eLearning synthesis of key takeaways from academics and students on co-creation."},
      {"title":"How student-staff partnership programs are transforming universities","org":"Various","url":"https://www.youtube.com/watch?v=5iJDPUcDRiQ","note":"Deakin University discussion exploring the systemic impact of partnership programs on governance."},
      {"title":"Power in Student/Staff Partnerships","org":"Various","url":"https://www.youtube.com/watch?v=sSEml-LJV0s","note":"WSU video addressing the negotiation of power dynamics and authority during co-creation projects."},
      {"title":"Some of the common misconceptions about Student Partnership","org":"Various","url":"https://www.youtube.com/watch?v=tjylWmuRcrg","note":"WSU breakdown addressing friction points and academic misunderstandings of SaP."},
      {"title":"Benefits for Staff – Working in partnership with students at UQ","org":"UQ","url":"https://www.youtube.com/watch?v=Vokmw-8_N6k","note":"How SaP changes academic practice, curriculum design, and staff perspectives."},
      {"title":"Benefits for Students – Working in partnership with staff at UQ","org":"UQ","url":"https://www.youtube.com/watch?v=ahax5t2K_mQ","note":"Focuses on student agency, academic socialization, and the shift to co-producers."},
      {"title":"Engaging Students as Partners in Learning","org":"USC Center for Teaching Excellence","url":"https://www.youtube.com/watch?v=isa73Gh3uqA","note":"Co-creation of courses using relational pedagogy to invite students into the learning process"},
      {"title":"Students as Partners for Sustainability","org":"Murdoch University / ACTS","url":"https://www.youtube.com/watch?v=4SGTBy31nOc","note":"Responsible Futures framework — embedding sustainability within curriculum and campus culture"},
      {"title":"BE SIG Webinar: Students as Partners","org":"ASCILITE (UTS, Griffith, Deakin, UQ)","url":"https://www.youtube.com/watch?v=TzlXttaYrm8","note":"Panel on the what, why, and how of SaP in Australian higher education"},
      {"title":"Considering Time in Students as Partners","org":"Center for Engaged Learning","url":"https://www.youtube.com/watch?v=gH_wqwdDpns","note":"How age, career stage, and historical moments shape SaP work"},
      {"title":"What Do Student Partners Actually Do?","org":"WSU Student Partners","url":"https://www.youtube.com/watch?v=tiJefH6jRrY","note":"Dr Tai Peseta on how students partner with staff to transform learning"},
      {"title":"The Future of Learning at UCD","org":"UCD Teaching and Learning","url":"https://www.youtube.com/watch?v=Jj6y49rODIo","note":"Student voice on AI and the future of university learning — created by UCD SaP"},
      {"title":"Assessment in Higher Education (Student Perspectives)","org":"UCD Teaching and Learning","url":"https://www.youtube.com/watch?v=rYrE140SO60","note":"Students share experiences with assessment styles — UCD SaP symposium"},
      {"title":"Centering Learner Voice Using a Students as Partners Model","org":"Nipissing University","url":"https://www.youtube.com/watch?v=OaFPClrfIlA","note":"Student and staff partners reflect on centering student voices in teaching spaces"},
      {"title":"Center for Engaged Learning: SoTL & Pedagogical Partnerships","org":"Center for Engaged Learning","url":"https://www.youtube.com/@centerforengagedlearning","note":"Repository of 60-Second SoTL videos, deep dives into pedagogical partnerships and equity"},
      {"title":"USC Center for Teaching Excellence Channel","org":"USC","url":"https://www.youtube.com/@usccenterforteachingexcell2411","note":"Detailed workshops on engaging students and co-creating course components"},
    ],
  },
  {
    id: "advising",
    title: "Academic Advising, Language & Transitions",
    subtitle: "First-year experience to lifelong academic support",
    blurb: "The STARS network, AALL communities, and institutional advising models supporting students through transition, retention, and academic language development.",
    icon: "🧭",
    videos: [
      {"title":"STARS conference vlog - the First Year Experience Network","org":"STARS","url":"https://www.youtube.com/watch?v=W9F8yJQW180","note":"Synthesis of key takeaways regarding first-year student transition and retention."},
      {"title":"Dr Ella Kahu – A Journey, a Rollacoaster or a Car Crash","org":"STARS","url":"https://www.youtube.com/watch?v=1rtrWSXHIBA","note":"Presentation on the emotional and cognitive transitions students face entering higher education."},
      {"title":"STARS conference vlog - ARTIFICIAL INTELLIGENCE and HIGHER EDUCATION","org":"STARS","url":"https://www.youtube.com/watch?v=Oy5yyHt4oYc","note":"Examining how AI is reshaping student support frameworks."},
      {"title":"STARS conference vlog on EMPLOYABILITY with Sally Kift & Angela Carbone","org":"STARS","url":"https://www.youtube.com/watch?v=6BgYLeSvXI8","note":"Discussion on embedding transition pedagogy and employability into the curriculum."},
      {"title":"STARS Conference vlog - the Psychological Wellbeing in Higher Education Network","org":"STARS","url":"https://www.youtube.com/watch?v=ZObej5HhuOU","note":"Insights into shifting advising to include holistic wellbeing checks."},
      {"title":"What’s New at the 2025 Indigenous All-Stars Conference? (Curtin University)","org":"STARS","url":"https://www.youtube.com/watch?v=4wY0CCj-fbk","note":"Look at Indigenous student transition, support, and success initiatives."},
      {"title":"AALL Symposium 2022 Discussion Panel - The impact of advising","org":"AALL","url":"https://www.youtube.com/watch?v=Lj5UJ0UrcNw","note":"Panel dissecting what constitutes the 'best advice' and impacts on retention."},
      {"title":"AALL Connect: Academic Skills Advising: A National Landscape 1-1s Snapshot","org":"AALL","url":"https://www.youtube.com/watch?v=71jzXPOrbIk","note":"How different Australian universities handle one-on-one academic advising."},
      {"title":"AALL Connect: Delivery and pedagogy of 1-1 Academic Skills advising","org":"AALL","url":"https://www.youtube.com/watch?v=AlFPfxSUge4","note":"Deep dive into pedagogical frameworks underpinning one-on-one student consultations."},
      {"title":"AALL Symposium 2024 Keynote & Session 2","org":"AALL","url":"https://www.youtube.com/watch?v=I-hk2iLSAQQ","note":"Latest trends in academic language support and advising across Australasia."},
      {"title":"AALL Symposium 2024 Session 3 & 4","org":"AALL","url":"https://www.youtube.com/watch?v=CYhpZCwFRLM","note":"Focusing on institutional implementations of language and learning frameworks."},
      {"title":"AALL 2022 Symposium Keynote - One small thing: a cause for optimism","org":"AALL","url":"https://www.youtube.com/watch?v=X_ZFp_Q0AJk","note":"Keynote on micro-interventions in advising that yield significant retention results."},
      {"title":"15th Biennial AALL Conference 2021: Keynote Speaker Alex Barthel","org":"AALL","url":"https://www.youtube.com/watch?v=fu1r9GuWf6A","note":"Historical and forward-looking perspective on academic language and learning in Australia."},
      {"title":"AALL Connect: Designing discipline-specific ALL workshops","org":"AALL","url":"https://www.youtube.com/watch?v=T-emuzgGOoM","note":"Targeted, discipline-specific language advising strategies."},
      {"title":"AALL Connect: Designing & advising on PowerPoint presentations for learners","org":"AALL","url":"https://www.youtube.com/watch?v=_DU5Nks-lAs","note":"Practical session on advising students on digital and visual communication skills."},
      {"title":"AALL Connect: Designing accessible learning resources","org":"AALL","url":"https://www.youtube.com/watch?v=X0Mdbh_f7sM","note":"Workshop on ensuring advising materials and academic support resources are universally accessible."},
      {"title":"How a student advisor can guide you (Open Universities Australia)","org":"Open Universities Australia","url":"https://www.youtube.com/watch?v=Uw4irxlHeKM","note":"A look at the institutional messaging and framework used to direct students to academic advisors."},
    ],
  },
  {
    id: "peer-learning",
    title: "Peer Learning, Assessment & Instruction",
    subtitle: "Students teaching students at scale",
    blurb: "PASS programs, peer assessment frameworks, audience response systems, and the growing evidence base for peer-to-peer learning in Australasian higher education.",
    icon: "👥",
    videos: [
      {"title":"Peer Learning in Australasia","org":"PASS","url":"https://www.youtube.com/watch?v=SYq15_1piKU","note":"Synthesis of how peer learning models have been adapted across Australian higher education."},
      {"title":"Overview of Australian Student Study Group Leader Interviews","org":"PASS","url":"https://www.youtube.com/watch?v=xR4REgwhwzo","note":"Thematic analysis of interviews with PASS leaders across the country."},
      {"title":"Interview with Martin, Student PASS Leader, Griffith Univ.","org":"PASS","url":"https://www.youtube.com/watch?v=R-4KiwzUFYY","note":"The student experience of facilitating peer-assisted study at Griffith University."},
      {"title":"Interview with Claire, Student PASS Leader, Univ. of South Australia","org":"PASS","url":"https://www.youtube.com/watch?v=qs3YiwX4ZeU","note":"Discussion on pedagogical strategies employed by student leaders at UniSA."},
      {"title":"Interview with Prahlad, Student PASS Leader, Marquarie Univ.","org":"PASS","url":"https://www.youtube.com/watch?v=0fCFqEMftMY","note":"Insights into managing engagement and resistance in peer-led groups."},
      {"title":"Peer-Assisted Study Sessions (Student Success Unit)","org":"PASS","url":"https://www.youtube.com/watch?v=EtCNM8P-A3g","note":"Breakdown of administrative and academic scaffolding for PASS programs."},
      {"title":"Peer Assisted Learning Sessions (PALS) at UC","org":"PASS","url":"https://www.youtube.com/watch?v=QszX_QzjxKE","note":"New Zealand equivalent model (University of Canterbury) demonstrating regional variations."},
      {"title":"Evaluation of peer assessment (UNSW CELEBS)","org":"UNSW CELEBS","url":"https://www.youtube.com/watch?v=iJbdNwozk7U","note":"How to validate and evaluate the effectiveness of peer marking."},
      {"title":"Teamwork development through self and peer assessment","org":"Various","url":"https://www.youtube.com/watch?v=KRHyCYNMJpk","note":"Using digital tools to facilitate equitable peer assessment within group work."},
      {"title":"Peer Assessment using the Survey tool","org":"Various","url":"https://www.youtube.com/watch?v=3EfYdn1T064","note":"Blended Learning Forum workshop on integrating peer marking protocols into LMS."},
      {"title":"Blackboard self and peer assessment: students evaluating team members","org":"LMS Tools","url":"https://www.youtube.com/watch?v=jpBtflddOCQ","note":"Walkthrough of setting up peer evaluation rubrics in Blackboard."},
      {"title":"Designing authentic exam questions (Transforming Assessment)","org":"Transforming Assessment","url":"https://www.youtube.com/watch?v=cJLVrRUBmQM","note":"Discussing how peer review can be integrated into high-stakes authentic assessment."},
      {"title":"The Role of the Lecturer in the Modern University","org":"Various","url":"https://www.youtube.com/watch?v=3uyiuf4QhQA","note":"UWA discussion on shifting to facilitating peer-to-peer instruction."},
      {"title":"Peer instruction and audience response systems","org":"Various","url":"https://www.youtube.com/watch?v=PwD29SSM1zU","note":"How real-time polling tools trigger immediate peer instruction in lectures."},
      {"title":"CANVA + peer instruction","org":"Blended Learning Forum","url":"https://www.youtube.com/watch?v=soNGuaJr9Pc","note":"Merging collaborative digital design tools with peer instructional models."},
      {"title":"Statbot – A friendly cognitive tutor (Liana Pozza et al., USyd)","org":"AI in HE Symposium 2026","url":"","note":"GenAI agent giving instant help with statistical concepts and R coding."},
    ],
  },
  {
    id: "prt",
    title: "Peer Review & Observation of Teaching",
    subtitle: "From performative observation to collegial dialogue",
    blurb: "Collegial review frameworks, classroom observation models, and the OLT PRoT project — shifting peer review from compliance to genuine professional growth.",
    icon: "🔍",
    videos: [
      {"title":"Peer Review — Perspectives","org":"Australian OLT PRoT Project","url":"https://www.youtube.com/watch?v=F51mQ9eC8Yc","note":"Academics reflect on shared responsibility for teaching quality and reciprocal review"},
      {"title":"Peer Review — Affect","org":"Australian OLT PRoT Project","url":"https://www.youtube.com/watch?v=zJg4RWeVl2U","note":"Emotional and vulnerable aspects of having teaching observed by colleagues"},
      {"title":"Peer Review — Communication","org":"Australian OLT PRoT Project","url":"https://www.youtube.com/watch?v=Muj11ABq69E","note":"Pre- and post-observation communication frameworks for formative peer review"},
      {"title":"Peer Review — Reporting","org":"Australian OLT PRoT Project","url":"https://www.youtube.com/watch?v=Gj8xP7A_kO8","note":"Documenting peer observation outcomes for promotions and teaching awards"},
      {"title":"Peer Review of Teaching: The Classroom Observation","org":"UBC CTLT","url":"https://www.youtube.com/watch?v=YC3qfB8uUaY","note":"Practical demonstration of conducting a live classroom observation"},
      {"title":"Peer Observation of Teaching","org":"UNSW","url":"https://www.youtube.com/watch?v=9_OqQ3aI_A4","note":"Community of practice through peer observation — sharing pedagogical strategies"},
      {"title":"Formative Peer Review of Teaching","org":"Various","url":"https://www.youtube.com/watch?v=kYJ7wz3eQh8","note":"Formative review for continuous PD rather than summative performance management"},
      {"title":"The Role of Peer Observation in Higher Ed","org":"Various","url":"https://www.youtube.com/watch?v=XQfB9Z7XW3s","note":"From performative to dialogic observation — building trust among teaching staff"},
    ],
  },
];

/** "International SoTL" — 7 themes, 83 curated talks. */
export const INTERNATIONAL_THEMES: readonly TalkTheme[] = [
  {
    id: "issotl",
    title: "ISSoTL & the Scholarship of Teaching and Learning",
    subtitle: "Felten, Shulman, and the intellectual foundations of SoTL",
    blurb: "The global SoTL movement — its history, key characteristics, controversies, and future directions — from the scholars who defined the field.",
    icon: "🌍",
    videos: [
      {"title":"Partnering With Students on Teaching and Learning","org":"ISSoTL / Peter Felten","url":"https://www.youtube.com/watch?v=pPU4ckBBeEU","note":"Students as partners in SoTL — Felten's foundational framing"},
      {"title":"Examples of SoTL Projects (Featuring Peter Felten)","org":"ISSoTL","url":"https://www.youtube.com/watch?v=LogmkiN6utk","note":"Concrete examples of what SoTL inquiry looks like in practice"},
      {"title":"Value of ISSoTL Membership","org":"ISSoTL","url":"https://www.youtube.com/watch?v=NmdwXJTt5yA","note":"The international SoTL community and its benefits"},
      {"title":"Key Characteristics of the Scholarship of Teaching and Learning","org":"ISSoTL","url":"https://www.youtube.com/watch?v=yvDKHHyx7YY","note":"What distinguishes SoTL from good teaching practice"},
      {"title":"Scholarship of Teaching and Learning vs. Scholarly Teaching","org":"ISSoTL","url":"https://www.youtube.com/watch?v=eedxoj1CPnk","note":"The critical distinction between SoTL and scholarly teaching"},
      {"title":"History of the Scholarship of Teaching and Learning","org":"ISSoTL","url":"https://www.youtube.com/watch?v=gYiyxQGa480","note":"From Boyer's 1990 framework to the contemporary global movement"},
      {"title":"Controversies, Debates, and Tensions in SoTL","org":"ISSoTL","url":"https://www.youtube.com/watch?v=mkkoJ2iVbGs","note":"Disciplinary boundaries, methodological tensions, and legitimacy"},
      {"title":"The Evolution of SoTL (Featuring Lee Shulman)","org":"ISSoTL","url":"https://www.youtube.com/watch?v=yDaOhCLic4k","note":"Lee Shulman — the intellectual trajectory from Pedagogical Content Knowledge"},
      {"title":"Future Directions and Emerging Trends in SoTL","org":"ISSoTL","url":"https://www.youtube.com/watch?v=RQHzseWH_j8","note":"Where the global SoTL movement is headed"},
      {"title":"Strategies for Going Public with SoTL","org":"ISSoTL","url":"https://www.youtube.com/watch?v=namehdJxRIM","note":"Publishing, presenting, and making SoTL visible"},
      {"title":"Global Perspectives on SoTL","org":"ISSoTL","url":"https://www.youtube.com/watch?v=w-JPTYjCnss","note":"Cross-cultural and cross-national approaches to SoTL"},
      {"title":"Entrevista a Peter Felten sobre SoTL (Spanish)","org":"ISSoTL","url":"https://www.youtube.com/watch?v=bTOCWM4k4Ns","note":"Spanish-language interview — SoTL's global reach beyond English"},
    ],
  },
  {
    id: "prog-assess",
    title: "Programmatic Assessment, Assurance of Learning & Feedback",
    subtitle: "Van der Vleuten, Schuwirth, Winstone — the global assessment redesign",
    blurb: "The Dutch school of programmatic assessment meets UK feedback literacy research — redefining how entire programs generate valid evidence of learning.",
    icon: "📊",
    videos: [
      {"title":"Programmatic Assessment in Medical Education","org":"Prof. Cees van der Vleuten","url":"https://www.youtube.com/watch?v=Ja4RqxSKoaY","note":"The foundational model — assessment as a system, not individual events"},
      {"title":"What Is Programmatic Assessment?","org":"Prof. Cees van der Vleuten","url":"https://www.youtube.com/watch?v=UEAT6_Avuas","note":"Core principles — low-stakes data points, high-stakes decisions"},
      {"title":"Overview of Programmatic Assessment","org":"Prof. Lambert Schuwirth","url":"https://www.youtube.com/watch?v=zBKPyCzrqQI","note":"Schuwirth's complementary framing of the programmatic model"},
      {"title":"Programmatic Assessment: Insights from Theory and Practice","org":"Dr Liesbeth Baartman","url":"https://www.youtube.com/watch?v=_ZK9XpK8dek","note":"Bridging theory and implementation — practical design insights"},
      {"title":"The Value of Programmatic Assessment Amid AI Disruption","org":"Programmatic Assessment","url":"https://www.youtube.com/watch?v=tNZIfR30534","note":"Why programmatic models are more resilient to AI than task-level ones"},
      {"title":"The Value of Programmatic Assessment","org":"Programmatic Assessment","url":"https://www.youtube.com/watch?v=uCEanlEZT84","note":"Institutional benefits of the programmatic approach"},
      {"title":"Feedback and Assessment Network with Dr Naomi Winstone","org":"Prof. Naomi Winstone","url":"https://www.youtube.com/watch?v=LaxjFznuKfE","note":"Building institutional feedback networks — UK research leadership"},
      {"title":"Recess: Feedback with Professor Naomi Winstone","org":"Prof. Naomi Winstone","url":"https://www.youtube.com/watch?v=dphgPQYIRM0","note":"Student-facing feedback literacy — closing the loop"},
    ],
  },
  {
    id: "active-learning",
    title: "Active Learning & Peer Instruction",
    subtitle: "Mazur, CMU Eberly Center — the evidence for active pedagogies",
    blurb: "Eric Mazur's Peer Instruction revolution and CMU's learning science — the empirical case for abandoning the traditional lecture and designing for active cognition.",
    icon: "💡",
    videos: [
      {"title":"Peer Instruction for Active Learning","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=FUY049rIjdM","note":"The core Peer Instruction model — conceptual understanding over memorisation"},
      {"title":"Getting Every Student Ready for Every Class","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=anAp5UIsGCA","note":"Pre-class preparation and the flipped classroom rationale"},
      {"title":"Eric Mazur Shows Interactive Teaching","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=wont2v_LZ1E","note":"Live demonstration of Peer Instruction in a physics lecture"},
      {"title":"Peer Instruction and Why Assessment Is a Killer of Learning","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=NrgHpwhiQ0Y","note":"How conventional assessment undermines deep learning"},
      {"title":"Assessment — The Silent Killer of Learning (Tour de Mazur)","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=6sY7UJCYbNg","note":"Extended keynote on assessment's perverse effects on cognition"},
      {"title":"Assessment — The Silent Killer of Learning","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=8sh6wsUFQT0","note":"Alternative version — assessment reform as pedagogical imperative"},
      {"title":"Confessions of a Converted Lecturer","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=FgcTHfg6GK0","note":"Mazur's famous talk on abandoning lectures — 3.5M+ views"},
      {"title":"Confessions of a Converted Lecturer (Extended)","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=3CTHZ-7EKbE","note":"Extended Edinburgh version with additional Q&A"},
      {"title":"Memorisation or Understanding: Are We Teaching the Right Thing?","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=tn1DLFnbGOo","note":"The Force Concept Inventory and what students actually learn"},
      {"title":"Transforming Education Through Computer Vision and Automated Assessment","org":"Eric Mazur / Harvard","url":"https://www.youtube.com/watch?v=51r1jx4__Mw","note":"AI and computer vision for scalable formative assessment"},
      {"title":"Adaptive Learning at CMU's Eberly Center","org":"CMU Eberly Center","url":"https://www.youtube.com/watch?v=nIq-xmnEBbI","note":"Carnegie Mellon's learning science approach to adaptive platforms"},
      {"title":"How Learning Works","org":"CMU Eberly Center","url":"https://www.youtube.com/watch?v=PkOYHiLbDnA","note":"Research-based principles of learning — the Eberly Center framework"},
      {"title":"Reviewing Student Progress","org":"CMU Eberly Center","url":"https://www.youtube.com/watch?v=MM8G1qJosmQ","note":"Data-informed approaches to monitoring student achievement"},
    ],
  },
  {
    id: "advance-he",
    title: "Advance HE & UK Professional Standards",
    subtitle: "PSF 2023, Fellowship, and inclusive HE practice",
    blurb: "The UK Professional Standards Framework for teaching in higher education — from AFHEA through PFHEA — and Advance HE's work on inclusivity, equity, and institutional enhancement.",
    icon: "🏛️",
    videos: [
      {"title":"Advance HE New to Teaching Programme","org":"Advance HE","url":"https://www.youtube.com/watch?v=4Qimt3IkJUQ","note":"Foundation programme for early-career HE teachers"},
      {"title":"Introduction to New to Teaching Programme","org":"Advance HE","url":"https://www.youtube.com/watch?v=pRSqj7fx-Nw","note":"Programme overview and learning outcomes"},
      {"title":"Professional Standards Framework (PSF)","org":"Advance HE","url":"https://www.youtube.com/watch?v=PVxnndR7SCs","note":"PSF 2023 overview — the global benchmark for HE teaching"},
      {"title":"How to Write a Powerful Senior HEA Fellowship Application","org":"Advance HE","url":"https://www.youtube.com/watch?v=pE0i4WHm7NM","note":"SFHEA application strategy — evidence, reflection, and impact"},
      {"title":"Writing a Successful Advance HE Fellowship Application","org":"Advance HE","url":"https://www.youtube.com/watch?v=-rowdj5DdPk","note":"General Fellowship application guidance across all categories"},
      {"title":"How to Get an Advance HE Fellowship (FHEA)","org":"Advance HE","url":"https://www.youtube.com/watch?v=bxcQMjQXWFM","note":"Step-by-step guide to achieving Fellow status"},
      {"title":"Enhance Teaching and Learning for Student and Institutional Success","org":"Advance HE","url":"https://www.youtube.com/watch?v=s6h5Hvu3AK8","note":"Commitment 4 — strategic enhancement of L&T at institutional level"},
      {"title":"Inclusive Teaching in Higher Education","org":"Advance HE","url":"https://www.youtube.com/watch?v=y1sIUDfWEvo","note":"Inclusive pedagogy frameworks and practical strategies"},
    ],
  },
  {
    id: "educause",
    title: "EDUCAUSE Horizon Reports & Technology Trends",
    subtitle: "Mapping the digital future of higher education",
    blurb: "EDUCAUSE's annual Horizon Reports and technology-focused research — the authoritative international guide to emerging technologies, digital trends, and student technology experiences.",
    icon: "🚀",
    videos: [
      {"title":"The 2026 EDUCAUSE Horizon Report: Teaching and Learning Edition","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=R8z1yTECbmY","note":"2026 edition — AI, XR, analytics, and the evolving classroom"},
      {"title":"Discussion on 2026 EDUCAUSE Horizon Report Findings","org":"EDUCAUSE","url":"https://www.youtube.com/shorts/VHknvZlz3g4","note":"Short-form discussion of key 2026 findings"},
      {"title":"2026 Students and Technology Report: Steady Through Change","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=T66Na_S4rOM","note":"Student technology experiences and expectations in 2026"},
      {"title":"2025 EDUCAUSE Horizon Report — Landscape","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=MfiD9xciPRg","note":"2025 landscape scan — institutional digital transformation"},
      {"title":"2025 EDUCAUSE Horizon Report — Trends","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=9emyo3X3a90","note":"Key trends shaping higher education technology"},
      {"title":"2025 EDUCAUSE Horizon Report — Evolving Teaching Practices","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=xgijANnNKFQ","note":"How teaching practices are changing in response to digital transformation"},
      {"title":"How to Use the HECVAT (Vendor Assessment Toolkit)","org":"EDUCAUSE","url":"https://www.youtube.com/watch?v=yC3_cK0e1bg","note":"Higher Education Cloud Vendor Assessment Tool for procurement"},
    ],
  },
  {
    id: "global-centres",
    title: "Global Centres for Teaching & Learning",
    subtitle: "UCL, Oxford, Yale, UBC, McGill, Toronto, Vanderbilt, CMU",
    blurb: "Teaching and learning innovation from the world's leading university centres — assessment design, peer review of teaching, active learning spaces, and institutional excellence.",
    icon: "🏛️",
    videos: [
      {"title":"Putting Educational Assessment to the Test","org":"UCL Institute of Education","url":"https://www.youtube.com/watch?v=Rt6LtKw2Y8I","note":"Critical examination of assessment validity and reliability"},
      {"title":"Education (Assessment) MA at UCL IoE","org":"UCL Institute of Education","url":"https://www.youtube.com/watch?v=8Y2bjUxrMzk","note":"Postgraduate assessment studies — research-informed practice"},
      {"title":"The Future Is Now (Dr Mary Richardson)","org":"UCL Institute of Education","url":"https://www.youtube.com/watch?v=GVEUm2iP1jY","note":"Forward-looking assessment design for uncertain futures"},
      {"title":"“The Teacher Is Our Best Resource”","org":"UCL Institute of Education","url":"https://www.youtube.com/watch?v=yoVewx7aUiA","note":"Valuing teacher expertise in educational assessment"},
      {"title":"Provost's Teaching Awards at UCL","org":"UCL","url":"https://www.youtube.com/watch?v=gKjqzQIvPh4","note":"Institutional recognition of teaching excellence"},
      {"title":"Luminaries: AI Tools and Assessment","org":"Oxford CTL","url":"https://www.youtube.com/watch?v=OrYmCpyqdA0","note":"Oxford Centre for Teaching and Learning — AI assessment futures"},
      {"title":"Creating a Source Category in Cabinet (Digital Objects)","org":"Oxford CTL","url":"https://www.youtube.com/watch?v=fbo6qdeyMEM","note":"Digital object management for teaching with primary sources"},
      {"title":"Ideas for Using Annotations in Cabinet","org":"Oxford CTL","url":"https://www.youtube.com/watch?v=x2T9bJorxXk","note":"Collaborative annotation for deep reading and critical analysis"},
      {"title":"Terminology for Teaching with Digital Objects","org":"Oxford CTL","url":"https://www.youtube.com/watch?v=IDc3YQjQoqA","note":"Shared vocabulary for digital pedagogy at Oxford"},
      {"title":"Classroom Assessment Techniques","org":"Vanderbilt CFT","url":"https://www.youtube.com/watch?v=qW9HKVaAGP4","note":"Angelo & Cross's CATs — quick formative assessment strategies"},
      {"title":"Engaging and Generative Assessments","org":"Vanderbilt CFT","url":"https://www.youtube.com/watch?v=fZmmuyQaUVA","note":"Assessment designs that promote deeper learning"},
      {"title":"How to Make an Assignment in Brightspace","org":"Vanderbilt CFT","url":"https://www.youtube.com/watch?v=KNn7ey8c34k","note":"LMS practical — integrating assessment into digital workflow"},
      {"title":"Learning Through Experience","org":"Yale Poorvu Center","url":"https://www.youtube.com/watch?v=k-7Xe61PcdE","note":"Experiential learning design at Yale"},
      {"title":"Making Group Work 'Work' with Active Learning","org":"Yale Poorvu Center","url":"https://www.youtube.com/watch?v=Ok2zICsBFOc","note":"Structuring collaborative learning for genuine engagement"},
      {"title":"Incorporating Accessibility into Teaching","org":"Yale Poorvu Center","url":"https://www.youtube.com/watch?v=iPixRnCP1ds","note":"Universal Design for Learning in practice"},
      {"title":"Teams Within Yale's Poorvu Center","org":"Yale Poorvu Center","url":"https://www.youtube.com/watch?v=fmQLhB4xY9s","note":"How Yale organises teaching and learning support"},
      {"title":"Presenting Evidence of Teaching Effectiveness","org":"UBC CTLT","url":"https://www.youtube.com/watch?v=QMVAtYgDLhg","note":"Teaching dossier and evidence-based promotion cases"},
      {"title":"Peer Review of Teaching Initiative","org":"UBC CTLT","url":"https://www.youtube.com/watch?v=ylj7iuofZik","note":"Institutional peer review models for teaching quality"},
      {"title":"Formative Peer Review of Teaching (Pre-Observation)","org":"UBC CTLT","url":"https://www.youtube.com/watch?v=f2j3L3WGbEs","note":"Pre-observation protocols for developmental peer review"},
      {"title":"Active Learning Classrooms","org":"McGill TLS","url":"https://www.youtube.com/watch?v=xFIDad64j8M","note":"Designing physical spaces for active collaborative learning"},
      {"title":"Design More Effective Rubrics","org":"McGill TLS","url":"https://www.youtube.com/watch?v=zsdYaBloKhI","note":"Rubric design principles for transparent assessment"},
      {"title":"Remote Assessment Strategies","org":"McGill TLS","url":"https://www.youtube.com/watch?v=qFUsn2zMfn8","note":"Assessment integrity and design for remote delivery"},
      {"title":"Getting Started: Research on Teaching","org":"U of Toronto CTSI","url":"https://www.youtube.com/watch?v=VFDJcElUIi8","note":"Launching SoTL projects — a practical orientation"},
      {"title":"Course Evaluation Summary Sheet","org":"U of Toronto CTSI","url":"https://www.youtube.com/watch?v=cVcUrE1ad3U","note":"Using course evaluation data for evidence-based teaching improvement"},
    ],
  },
  {
    id: "jisc-uk",
    title: "Jisc — Beyond Blended & Digital Education (UK)",
    subtitle: "Curriculum design, learning analytics, AI literacy & digital transformation",
    blurb: "The UK's digital education agency. Its \"Beyond the Technology\" series spans blended & curriculum design, learning analytics, AI literacy and accessibility — the UK counterpart to Australia's digital-education conversation.",
    icon: "🇬🇧",
    videos: [
      {"title":"Beyond Blended in Action: Voices from the Sector","org":"Jisc","url":"https://www.youtube.com/watch?v=3qLDardwwwo","note":"Findings from Jisc's 17-provider Beyond Blended pilot — curriculum & learning design in practice."},
      {"title":"AI Literacy for Teaching & Learning — Module 1: Understanding AI","org":"Jisc","url":"https://www.youtube.com/watch?v=MokwnbtJEdM","note":"Preview of Jisc's AI-literacy digital module for educators."},
      {"title":"Turning Learning Analytics into Meaningful Conversations","org":"Jisc","url":"https://www.youtube.com/watch?v=Jt4sTSa1FGE","note":"Beyond the Technology — using analytics to support, not surveil, students."},
      {"title":"Learning Analytics for Compliance, Engagement & Student Success","org":"Jisc","url":"https://www.youtube.com/watch?v=G0RYNGq48vs","note":"How Jisc learning analytics supports student success."},
      {"title":"Improving Student Retention with Learning Analytics","org":"Jisc","url":"https://www.youtube.com/watch?v=XKmCSSmlDXo","note":"Data-informed retention strategies."},
      {"title":"Leading Change: What Creative Universities Know About Digital Innovation","org":"Jisc","url":"https://www.youtube.com/watch?v=qjjbzl733OY","note":"Digital innovation leadership in higher education."},
      {"title":"Embedding Digital Confidence at Every Level","org":"Jisc","url":"https://www.youtube.com/watch?v=eZ0spwX9IR4","note":"Beyond the Technology — building staff & student digital capability."},
      {"title":"From Practitioners to Digital Leaders","org":"Jisc","url":"https://www.youtube.com/watch?v=S7wTueB01g4","note":"Beyond the Technology — growing digital leadership."},
      {"title":"Digital Transformation in Scottish Colleges","org":"Jisc","url":"https://www.youtube.com/watch?v=m3hKUQ9lX6g","note":"Beyond the Technology — sector-wide digital transformation."},
      {"title":"How Libraries Contribute to Shaping Digital Transformation","org":"Jisc","url":"https://www.youtube.com/watch?v=nxTEDOLVTrY","note":"Beyond the Technology — the library's role in change."},
      {"title":"Accessibility Community Drop-in (March 2026)","org":"Jisc","url":"https://www.youtube.com/watch?v=rjdr9bI_vxk","note":"Jisc's accessibility community of practice."},
    ],
  },
];

/**
 * Short chip labels for the sector theme rail — the bundle's id-to-label
 * map, verbatim (the chips show these, not the long theme titles).
 */
export const SECTOR_CHIP_LABELS: Readonly<Record<string, string>> = {
  genai: "GenAI",
  assessment: "Assessment",
  indigenous: "Indigenising",
  "sotl-praxis": "SoTL Praxis",
  tel: "TEL & Analytics",
  symposia: "Symposia",
  "sankey-digital": "Digital Leadership",
  udl: "UDL & Inclusion",
  sap: "Students as Partners",
  advising: "Advising & Transitions",
  "peer-learning": "Peer Learning",
  prt: "Peer Review",
};

/** Derived totals — never hardcode these in copy (CLAUDE.md). */
export const SECTOR_VIDEO_COUNT = SECTOR_THEMES.reduce(
  (n, t) => n + t.videos.length,
  0,
);
export const INTERNATIONAL_VIDEO_COUNT = INTERNATIONAL_THEMES.reduce(
  (n, t) => n + t.videos.length,
  0,
);

/** Extract a YouTube video id from any of the usual URL shapes. */
export function youTubeId(url: string): string | null {
  const m =
    url.match(/[?&]v=([\w-]{11})/) ??
    url.match(/youtu\.be\/([\w-]{11})/) ??
    url.match(/\/embed\/([\w-]{11})/);
  return m ? m[1] : null;
}

/** Extract a Vimeo video id, if the URL is a Vimeo link. */
export function vimeoId(url: string): string | null {
  const m = url.match(/vimeo\.com\/(\d+)/);
  return m ? m[1] : null;
}

/**
 * Filter a theme's videos by search query — the bundle's exact match rule
 * (case-insensitive substring across title, note and org).
 */
export function filterThemeVideos(
  theme: TalkTheme,
  query: string,
): TalkVideo[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...theme.videos];
  return theme.videos.filter(
    (v) =>
      v.title.toLowerCase().includes(q) ||
      v.note.toLowerCase().includes(q) ||
      v.org.toLowerCase().includes(q),
  );
}

/**
 * The "Sources: …" line under a theme banner — unique org names with the
 * bundle's exact truncation rule (drop " / …" and " (…" suffixes).
 */
export function sourcesLine(videos: readonly TalkVideo[]): string {
  return Array.from(
    new Set(videos.map((v) => v.org.split(" /")[0].split(" (")[0])),
  ).join(", ");
}
