/**
 * Canonical section order — extracted verbatim from the `ntlsn-order` patch
 * script in the production index.html (the ORDER array). Only the
 * id-addressable entries are listed here; the patch script's tag/regex
 * matchers (Due Soon, "What the data shows", Peak Bodies, etc.) address
 * anonymous bundle DOM and will gain ids as their sections are ported
 * (TASKS.md 1.2).
 *
 * Do NOT reorder: anchor compatibility with production depends on these ids
 * appearing in exactly this sequence (see tests/smoke.spec.js test (d)).
 */
export const SECTION_ORDER: readonly string[] = [
  "hero",
  "ntlsn-nowbanner",
  "ntlsn-startgrid",
  "ntlsn-freshtoday",
  "ntlsn-glance",
  "yearview",
  "events",
  "sotl-grants",
  "ntlsn-conference",
  "conferences",
  "ntlsn-zoom",
  "ntlsn-archive",
  "ntlsn-repository",
  "ntlsn-oer",
  "resources",
  "teaching-resources",
  "ntlsn-bestpractice",
  "ntlsn-talkshub",
  "sector-themes",
  "featured-talks",
  "ntlsn-latest",
  "international-themes",
  "ntlsn-frameworks-stage",
  "frameworks",
  "ntlsn-prx",
  "ntlsn-calibrate",
  "ntlsn-pairreview",
  "ntlsn-coursecheck",
  "ntlsn-curriculum",
  "ntlsn-diagnostic",
  "ntlsn-academy",
  "ntlsn-itonboard",
  "ntlsn-sprintplan",
  "ntlsn-abstractpreview",
  "ntlsn-evidencelib",
  "ntlsn-mcp",
  "ntlsn-pipeline",
  "ntlsn-policy",
  "ntlsn-dashboard",
  "ntlsn-recovery",
  "ntlsn-eba",
  "ntlsn-copscan",
  "ntlsn-journal",
  "ntlsn-capabilities",
  "pd",
  "ntlsn-waystogrow",
  "ntlsn-toolkit",
  "ntlsn-guided",
  "ntlsn-recognition",
  "ntlsn-showcase",
  "ntlsn-aaut",
  "ntlsn-natcert",
  "ntlsn-confrecognition",
  "ntlsn-passport",
  "ntlsn-pathfinder",
  "ntlsn-consortium",
  "ntlsn-sap",
  "ntlsn-service",
  "ntlsn-praise",
  "ntlsn-promotion",
  "ntlsn-rpcalc",
  "architecture",
  "map",
  "directory",
  "ntlsn-peakmap",
  "ntlsn-network",
  "pathways",
  "ntlsn-scrollconnect",
  "benchmarks",
  "ntlsn-fnawards",
  "ntlsn-oep",
  "ntlsn-whatsavailable",
  "ntlsn-trynow",
  "ntlsn-symshow",
  "ntlsn-principles",
  "ntlsn-ethos",
  "ntlsn-litmus",
  "ntlsn-challenges",
  "ntlsn-induction",
  "ntlsn-positionality",
  "ntlsn-advisory",
  "ntlsn-representation",
  "ntlsn-aim",
  "ntlsn-rebalance",
  "ntlsn-together",
  "ntlsn-distribute",
  "ntlsn-mission",
  "ntlsn-scope",
  "about",
  "ntlsn-coming2027",
  "ntlsn-coming2028",
  "pricing",
  "ntlsn-choosepackage",
  "ntlsn-allinone",
  "ntlsn-howitworks",
  "ntlsn-byrole",
  "ntlsn-tailored",
  "ntlsn-founding10",
  "ntlsn-member",
];

/** Human-readable label for a placeholder section, derived from its id. */
export function sectionLabel(id: string): string {
  const special: Record<string, string> = {
    yearview: "Year View",
    events: "What's On",
    "sotl-grants": "SoTL Grants",
    conferences: "Conferences",
    resources: "Resources",
    frameworks: "Frameworks",
    pd: "Professional Development",
    map: "National Map",
    directory: "Directory",
    pathways: "Pathways",
    benchmarks: "Benchmarks",
    about: "About",
    pricing: "Pricing",
    architecture: "Architecture",
    "ntlsn-oer": "OER",
    "ntlsn-mcp": "MCP",
    "ntlsn-eba": "EBA",
    "ntlsn-aaut": "AAUT",
    "ntlsn-sap": "Students as Partners",
    "ntlsn-oep": "Open Educational Practice",
  };
  if (special[id]) return special[id];
  return id
    .replace(/^ntlsn-/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
